### ISSUE TITLE
"Read more" filter

### ISSUE THREAD

**Issue by vytya** [CherryFramework/cherry-real-estate#7]
### What did you expect to happen?

Need to change 'read more' button text.
### What happened instead?

In shortcode we can change button text, but at search results page are default value, that I can't find how change it.

Can you provide a link to a page which shows this issue?
https://github.com/CherryFramework/cherry-real-estate/blob/master/includes/class-cherry-re-template-callbacks.php#L313

**Comment by cheh** [comment]
https://github.com/CherryFramework/cherry-real-estate/commit/ee5b377a0af1b31a0bc585738b3d33a6c203f37c
